In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
os.listdir("/content/drive/MyDrive/IRS Project ")

['Proposal Agenda.pptx', 'Yelp_Data.ipynb', 'okcupid_profiles.csv']

In [13]:
import pandas as pd

file_path =  "/content/drive/MyDrive/IRS Project /okcupid_profiles.csv"

df = pd.read_csv(file_path)

print(df.shape)
df.head()

(59946, 31)

,age,status,sex,orientation,body_type,diet,drinks,drugs,education,ethnicity,...,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9
0,22,single,m,straight,a little extra,strictly anything,socially,never,working on college/university,"asian, white",...,about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...
1,35,single,m,straight,average,mostly other,often,sometimes,working on space camp,white,...,i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,NaN,NaN,i am very open and will share just about anyth...,NaN
2,38,available,m,straight,thin,anything,socially,NaN,graduated from masters program,NaN,...,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,NaN,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ..."
3,23,single,m,straight,thin,vegetarian,socially,NaN,working on college/university,white,...,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",NaN,cats and german philosophy,NaN,NaN,you feel so inclined.
4,29,single,m,straight,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",...,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",NaN,NaN,NaN,NaN,NaN

In [14]:
print(df.columns.tolist())

['age', 'status', 'sex', 'orientation', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'ethnicity', 'height', 'income', 'job', 'last_online', 'location', 'offspring', 'pets', 'religion', 'sign', 'smokes', 'speaks', 'essay0', 'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7', 'essay8', 'essay9']

In [17]:

# Find all essay columns automatically
essay_cols = [col for col in df.columns if col.startswith("essay")]

# Columns we want to keep
keep_cols = [
    "age",
    "diet",
    "location"
] + essay_cols

# Keep only those columns
df = df[keep_cols].copy()

# Fill missing essays
df[essay_cols] = df[essay_cols].fillna("")

# Add a unique user ID
df = df.reset_index(drop=True)
df["user_id"] = ["U" + str(i).zfill(5) for i in range(len(df))]

print(df.columns.tolist())
df.head()

['age', 'diet', 'location', 'essay0', 'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7', 'essay8', 'essay9', 'user_id']

,age,diet,location,essay0,essay1,essay2,essay3,essay4,essay5,essay6,essay7,essay8,essay9,user_id
0,22,strictly anything,"south san francisco, california",about me: i would love to think that i was so...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...,U00000
1,35,mostly other,"oakland, california",i am a chef: this is what that means. 1. i am ...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,,,i am very open and will share just about anyth...,,U00001
2,38,anything,"san francisco, california","i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,okay this is where the cultural matrix gets so...,movement conversation creation contemplation t...,,viewing. listening. dancing. talking. drinking...,"when i was five years old, i was known as ""the...","you are bright, open, intense, silly, ironic, ...",U00002
3,23,vegetarian,"berkeley, california",i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",,cats and german philosophy,,,you feel so inclined.,U00003
4,29,NaN,"san francisco, california",hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",,,,,,U00004

In [19]:
#combine essays into one user context

essay_cols = [
    col for col in df.columns
    if col.startswith("essay")
]

df[essay_cols] = df[essay_cols].fillna("")

df["profile_text"] = df[essay_cols].agg(
    "\n".join,
    axis=1
)

df[["age","profile_text"]].head()

   age                                       profile_text
0   22  about me:  i would love to think that i was so...
1   35  i am a chef: this is what that means. 1. i am ...
2   38  i'm not ashamed of much, but writing public te...
3   23  i work in a library and go to school. . .\nrea...
4   29  hey how's it going? currently vague on the pro...

In [21]:
!pip install -q transformers accelerate bitsandbytes sentencepiece

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 36.7 MB/s eta 0:00:00

In [22]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

config.json:   0%|          | 0.00/661 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [23]:
def build_prompt(profile_text):

    return f"""
You are extracting user interests for an activity recommender system.

From the following profile, extract only interests that could help recommend:
- activities
- restaurants
- cafes
- events
- travel experiences
- entertainment
- outdoor activities
- cultural places

Return valid JSON only.

Use this structure:

{{
  "hobbies": [],
  "music_genres": [],
  "music_vibes": [],
  "food_interests": [],
  "sports": [],
  "outdoor_activities": [],
  "indoor_activities": [],
  "arts_culture": [],
  "nightlife": [],
  "travel_interests": [],
  "activity_vibes": []
}}

Rules:
- Do not invent interests.
- Extract only what is stated or strongly implied.
- Ignore dating preferences.
- Ignore sex, orientation, religion, ethnicity, and appearance.
- Normalize similar concepts.
- Use short phrases.

PROFILE:
{profile_text}
"""

In [24]:
def extract_interests(profile_text):

    prompt = build_prompt(profile_text)

    messages = [
        {"role": "user", "content": prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=400,
        temperature=0.1,
        do_sample=False
    )

    result = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True
    )

    return result

In [25]:
result = extract_interests(df.loc[0, "profile_text"])

print(result)

[transformers] The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

```json
{
  "hobbies": ["reading", "watching movies", "playing video games"],
  "music_genres": ["alternative rock", "punk rock"],
  "music_vibes": ["serious", "thought-provoking"],
  "food_interests": ["delicious food", "comfort food"],
  "sports": [],
  "outdoor_activities": [],
  "indoor_activities": ["reading", "watching movies", "playing video games"],
  "arts_culture": ["philosophy", "literature"],
  "nightlife": [],
  "travel_interests": [],
  "activity_vibes": ["intellectual", "funny", "serious"]
}
```